@startuml
!include <C4/C4_Container>

title AulaViva - C4 Nivel 2 Contenedores


Person(usuario,
"Usuarios AulaViva",
"Estudiantes, docentes, apoderados y administradores")


System_Boundary(aulaviva,"AulaViva"){


Container(web,
"Aplicación Web",
"React / Next.js",
"Interfaz principal para usuarios")


Container(api,
"Backend API",
"Node.js NestJS",
"Lógica de negocio del sistema")


Container(auth,
"Servicio Seguridad",
"JWT + RBAC",
"Autenticación, roles y permisos")


Container(tutor,
"Tutor IA",
"RAG + LLM",
"Respuestas contextualizadas")


Container(eval,
"Motor Evaluaciones",
"Servicio IA",
"Generación automática de evaluaciones")


Container(db,
"Base de Datos Multi-Tenant",
"PostgreSQL",
"Usuarios, cursos, notas y colegios")


Container(queue,
"Cola de Procesamiento",
"RabbitMQ",
"Procesos asíncronos")


}


System_Ext(email,
"Servicio Notificaciones",
"Correos y alertas")


System_Ext(mineduc,
"MINEDUC",
"Información curricular")


Rel(usuario,web,
"Utiliza")


Rel(web,api,
"Consume API REST")


Rel(api,auth,
"Valida permisos")


Rel(api,tutor,
"Consulta Tutor IA")


Rel(api,eval,
"Solicita evaluaciones")


Rel(api,db,
"Lee y almacena datos")


Rel(api,queue,
"Envía procesos")


Rel(queue,email,
"Genera notificaciones")


Rel(api,mineduc,
"Consulta referencias curriculares")


@enduml
