@startuml AulaViva_C4_L2

!include <C4/C4_Container>

Person(estudiante, "Estudiante")
Person(docente, "Docente")
Person(apoderado, "Apoderado")

System_Boundary(aula, "AulaViva Plataforma SaaS") {

Container(web, "Aplicación Web", "React / Next.js", "Interfaz para usuarios")

Container(api, "Backend API", "Node.js", "Lógica del sistema")

ContainerDb(db, "Base de Datos", "PostgreSQL", "Datos académicos")

Container(ai, "Tutor IA", "Python + LangChain", "Asistente inteligente")

ContainerDb(vector, "Base Vectorial", "ChromaDB", "Embeddings")

Container(email, "Servicio Email", "SMTP", "Notificaciones")

}

Rel(estudiante, web, "Usa")
Rel(docente, web, "Administra")
Rel(apoderado, web, "Consulta")

Rel(web, api, "HTTPS")
Rel(api, db, "Consulta datos")
Rel(api, ai, "Solicita respuestas")
Rel(ai, vector, "Busca información")
Rel(api, email, "Envía avisos")

@enduml
