/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/schools/{schoolId}/courses/{courseId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar contenido del curso
         * @description Acceso: docente, estudiante matriculado. El JWT debe autorizar schoolId. Recursos ajenos al colegio retornan 404 sin revelar su existencia.
         */
        get: operations["listContent"];
        put?: never;
        /**
         * Crear contenido educativo
         * @description Acceso: docente autorizado. El JWT debe autorizar schoolId. Recursos ajenos al colegio retornan 404 sin revelar su existencia.
         */
        post: operations["createContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/{schoolId}/students/{studentId}/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar notas del estudiante
         * @description Acceso: docente, estudiante titular, apoderado vinculado. El JWT debe autorizar schoolId. Recursos ajenos al colegio retornan 404 sin revelar su existencia.
         */
        get: operations["listGrades"];
        put?: never;
        /**
         * Registrar nota del estudiante
         * @description Acceso: docente autorizado. El JWT debe autorizar schoolId. Recursos ajenos al colegio retornan 404 sin revelar su existencia.
         */
        post: operations["createGrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/{schoolId}/students/{studentId}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener informe académico del estudiante
         * @description Acceso: docente, estudiante titular, apoderado vinculado. El JWT debe autorizar schoolId. Recursos ajenos al colegio retornan 404 sin revelar su existencia.
         */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/{schoolId}/courses/{courseId}/tutor-queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consultar tutor IA del curso
         * @description Acceso: docente, estudiante matriculado. El JWT debe autorizar schoolId. Recursos ajenos al colegio retornan 404 sin revelar su existencia.
         */
        post: operations["createTutorQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/{schoolId}/courses/{courseId}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generar borrador de evaluación
         * @description Acceso: docente autorizado. El JWT debe autorizar schoolId. Recursos ajenos al colegio retornan 404 sin revelar su existencia.
         */
        post: operations["createEvaluation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "title": "Guía de álgebra",
         *       "description": "Ecuaciones de primer grado",
         *       "fileUrl": "https://example.org/algebra.pdf"
         *     }
         */
        ContentInput: {
            title: string;
            description?: string;
            /** Format: uri */
            fileUrl: string;
        };
        /**
         * @example {
         *       "subject": "Matemáticas",
         *       "score": 6.5,
         *       "weight": 0.3,
         *       "comment": "Buen desempeño"
         *     }
         */
        GradeInput: {
            subject: string;
            score: number;
            weight?: number;
            comment?: string;
        };
        /**
         * @example {
         *       "studentId": "stu_01",
         *       "studentName": "Estudiante de prueba",
         *       "generalAverage": 6.2,
         *       "attendancePercentage": 94.5
         *     }
         */
        Report: {
            studentId: string;
            studentName: string;
            generalAverage: number;
            attendancePercentage: number;
        };
        /**
         * @example {
         *       "question": "¿Cómo resuelvo una ecuación de primer grado?"
         *     }
         */
        TutorQueryInput: {
            question: string;
        };
        /**
         * @example {
         *       "id": "tq_01",
         *       "answer": "Aísla la incógnita aplicando la misma operación a ambos lados.",
         *       "contentIds": [
         *         "cnt_01"
         *       ]
         *     }
         */
        TutorQuery: {
            id: string;
            answer: string;
            contentIds: string[];
        };
        /**
         * @example {
         *       "title": "Evaluación de álgebra",
         *       "contentIds": [
         *         "cnt_01"
         *       ],
         *       "questionCount": 5
         *     }
         */
        EvaluationInput: {
            title: string;
            contentIds: string[];
            questionCount: number;
        };
        /**
         * @example {
         *       "id": "ev_01",
         *       "title": "Evaluación de álgebra",
         *       "questions": [
         *         {
         *           "prompt": "Resuelve x + 2 = 5",
         *           "answer": "x = 3"
         *         }
         *       ],
         *       "status": "draft"
         *     }
         */
        Evaluation: {
            id: string;
            title: string;
            questions: {
                prompt: string;
                answer: string;
            }[];
            /** @enum {string} */
            status: "draft";
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            /** Format: uri-reference */
            instance: string;
            trace_id: string;
        };
        /**
         * @example {
         *       "id": "cnt_01",
         *       "title": "Guía de álgebra",
         *       "description": "Ecuaciones de primer grado",
         *       "fileUrl": "https://example.org/algebra.pdf",
         *       "createdAt": "2026-10-08T00:00:00Z"
         *     }
         */
        Content: {
            title: string;
            description?: string;
            /** Format: uri */
            fileUrl: string;
            id: string;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @example {
         *       "id": "grd_01",
         *       "subject": "Matemáticas",
         *       "score": 6.5,
         *       "weight": 0.3,
         *       "comment": "Buen desempeño",
         *       "date": "2026-10-08"
         *     }
         */
        Grade: {
            subject: string;
            score: number;
            weight?: number;
            comment?: string;
            id: string;
            /** Format: date */
            date: string;
        };
        /**
         * @example {
         *       "items": [
         *         {
         *           "id": "cnt_01",
         *           "title": "Guía de álgebra",
         *           "description": "Ecuaciones de primer grado",
         *           "fileUrl": "https://example.org/algebra.pdf",
         *           "createdAt": "2026-10-08T00:00:00Z"
         *         }
         *       ],
         *       "nextCursor": null
         *     }
         */
        ContentPage: {
            items: components["schemas"]["Content"][];
            nextCursor: string | null;
        };
        /**
         * @example {
         *       "items": [
         *         {
         *           "id": "grd_01",
         *           "subject": "Matemáticas",
         *           "score": 6.5,
         *           "weight": 0.3,
         *           "comment": "Buen desempeño",
         *           "date": "2026-10-08"
         *         }
         *       ],
         *       "nextCursor": null
         *     }
         */
        GradePage: {
            items: components["schemas"]["Grade"][];
            nextCursor: string | null;
        };
    };
    responses: {
        /** @description Solicitud inválida */
        400: {
            headers: {
                /**
                 * @description Identificador para correlacionar respuesta y logs.
                 * @example trace_demo_01
                 */
                "X-Trace-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://example.org/problems/400",
                 *       "title": "Solicitud inválida",
                 *       "status": 400,
                 *       "detail": "Solicitud inválida. Datos ficticios de demostración.",
                 *       "instance": "/api/v1/schools/sch_01/courses/crs_01/content",
                 *       "trace_id": "trace_demo_01"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Autenticación requerida */
        401: {
            headers: {
                /**
                 * @description Identificador para correlacionar respuesta y logs.
                 * @example trace_demo_01
                 */
                "X-Trace-Id"?: string;
                /**
                 * @description Desafío Bearer.
                 * @example Bearer
                 */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://example.org/problems/401",
                 *       "title": "Autenticación requerida",
                 *       "status": 401,
                 *       "detail": "Autenticación requerida. Datos ficticios de demostración.",
                 *       "instance": "/api/v1/schools/sch_01/courses/crs_01/content",
                 *       "trace_id": "trace_demo_01"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Permiso insuficiente */
        403: {
            headers: {
                /**
                 * @description Identificador para correlacionar respuesta y logs.
                 * @example trace_demo_01
                 */
                "X-Trace-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://example.org/problems/403",
                 *       "title": "Permiso insuficiente",
                 *       "status": 403,
                 *       "detail": "Permiso insuficiente. Datos ficticios de demostración.",
                 *       "instance": "/api/v1/schools/sch_01/courses/crs_01/content",
                 *       "trace_id": "trace_demo_01"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Recurso no encontrado */
        404: {
            headers: {
                /**
                 * @description Identificador para correlacionar respuesta y logs.
                 * @example trace_demo_01
                 */
                "X-Trace-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://example.org/problems/404",
                 *       "title": "Recurso no encontrado",
                 *       "status": 404,
                 *       "detail": "Recurso no encontrado. Datos ficticios de demostración.",
                 *       "instance": "/api/v1/schools/sch_01/courses/crs_01/content",
                 *       "trace_id": "trace_demo_01"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Conflicto de idempotencia */
        409: {
            headers: {
                /**
                 * @description Identificador para correlacionar respuesta y logs.
                 * @example trace_demo_01
                 */
                "X-Trace-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://example.org/problems/409",
                 *       "title": "Conflicto de idempotencia",
                 *       "status": 409,
                 *       "detail": "Conflicto de idempotencia. Datos ficticios de demostración.",
                 *       "instance": "/api/v1/schools/sch_01/courses/crs_01/content",
                 *       "trace_id": "trace_demo_01"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Validación semántica fallida */
        422: {
            headers: {
                /**
                 * @description Identificador para correlacionar respuesta y logs.
                 * @example trace_demo_01
                 */
                "X-Trace-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://example.org/problems/422",
                 *       "title": "Validación semántica fallida",
                 *       "status": 422,
                 *       "detail": "Validación semántica fallida. Datos ficticios de demostración.",
                 *       "instance": "/api/v1/schools/sch_01/courses/crs_01/content",
                 *       "trace_id": "trace_demo_01"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Límite de solicitudes excedido */
        429: {
            headers: {
                /**
                 * @description Identificador para correlacionar respuesta y logs.
                 * @example trace_demo_01
                 */
                "X-Trace-Id"?: string;
                /**
                 * @description Segundos antes de reintentar.
                 * @example 60
                 */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://example.org/problems/429",
                 *       "title": "Límite de solicitudes excedido",
                 *       "status": 429,
                 *       "detail": "Límite de solicitudes excedido. Datos ficticios de demostración.",
                 *       "instance": "/api/v1/schools/sch_01/courses/crs_01/content",
                 *       "trace_id": "trace_demo_01"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Servicio temporalmente no disponible */
        503: {
            headers: {
                /**
                 * @description Identificador para correlacionar respuesta y logs.
                 * @example trace_demo_01
                 */
                "X-Trace-Id"?: string;
                /**
                 * @description Segundos antes de reintentar.
                 * @example 60
                 */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://example.org/problems/503",
                 *       "title": "Servicio temporalmente no disponible",
                 *       "status": 503,
                 *       "detail": "Servicio temporalmente no disponible. Datos ficticios de demostración.",
                 *       "instance": "/api/v1/schools/sch_01/courses/crs_01/content",
                 *       "trace_id": "trace_demo_01"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description Identificador del recurso dentro del colegio autorizado.
         * @example sch_01
         */
        schoolId: string;
        /**
         * @description Identificador del recurso dentro del colegio autorizado.
         * @example crs_01
         */
        courseId: string;
        /**
         * @description Identificador del recurso dentro del colegio autorizado.
         * @example stu_01
         */
        studentId: string;
        /**
         * @description Tamaño de página (máximo 100).
         * @example 20
         */
        Limit: number;
        /**
         * @description Cursor opaco devuelto en nextCursor, limitado al tenant y filtros.
         * @example page_02
         */
        Cursor: string;
        /**
         * @description Filtrar notas por nombre exacto de asignatura.
         * @example Matemáticas
         */
        Subject: string;
        /**
         * @description UUID. Retención de 24 h por colegio, usuario y operación. Mismo payload reproduce status/body; payload diferente retorna 409.
         * @example 60fae59e-e41c-4fe9-8a7a-51c8e3a301cc
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listContent: {
        parameters: {
            query?: {
                /**
                 * @description Tamaño de página (máximo 100).
                 * @example 20
                 */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description Cursor opaco devuelto en nextCursor, limitado al tenant y filtros.
                 * @example page_02
                 */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example sch_01
                 */
                schoolId: components["parameters"]["schoolId"];
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example crs_01
                 */
                courseId: components["parameters"]["courseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consulta exitosa. */
            200: {
                headers: {
                    /**
                     * @description Identificador para correlacionar respuesta y logs.
                     * @example trace_demo_01
                     */
                    "X-Trace-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "cnt_01",
                     *           "title": "Guía de álgebra",
                     *           "description": "Ecuaciones de primer grado",
                     *           "fileUrl": "https://example.org/algebra.pdf",
                     *           "createdAt": "2026-10-08T00:00:00Z"
                     *         }
                     *       ],
                     *       "nextCursor": null
                     *     }
                     */
                    "application/json": components["schemas"]["ContentPage"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            429: components["responses"]["429"];
            503: components["responses"]["503"];
        };
    };
    createContent: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description UUID. Retención de 24 h por colegio, usuario y operación. Mismo payload reproduce status/body; payload diferente retorna 409.
                 * @example 60fae59e-e41c-4fe9-8a7a-51c8e3a301cc
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example sch_01
                 */
                schoolId: components["parameters"]["schoolId"];
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example crs_01
                 */
                courseId: components["parameters"]["courseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "title": "Guía de álgebra",
                 *       "description": "Ecuaciones de primer grado",
                 *       "fileUrl": "https://example.org/algebra.pdf"
                 *     }
                 */
                "application/json": components["schemas"]["ContentInput"];
            };
        };
        responses: {
            /** @description Recurso creado. */
            201: {
                headers: {
                    /**
                     * @description Identificador para correlacionar respuesta y logs.
                     * @example trace_demo_01
                     */
                    "X-Trace-Id"?: string;
                    /**
                     * @description URI del recurso creado dentro del colegio.
                     * @example /courses/crs_01/content/cnt_01
                     */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "cnt_01",
                     *       "title": "Guía de álgebra",
                     *       "description": "Ecuaciones de primer grado",
                     *       "fileUrl": "https://example.org/algebra.pdf",
                     *       "createdAt": "2026-10-08T00:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Content"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            503: components["responses"]["503"];
        };
    };
    listGrades: {
        parameters: {
            query?: {
                /**
                 * @description Tamaño de página (máximo 100).
                 * @example 20
                 */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description Cursor opaco devuelto en nextCursor, limitado al tenant y filtros.
                 * @example page_02
                 */
                cursor?: components["parameters"]["Cursor"];
                /**
                 * @description Filtrar notas por nombre exacto de asignatura.
                 * @example Matemáticas
                 */
                subject?: components["parameters"]["Subject"];
            };
            header?: never;
            path: {
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example sch_01
                 */
                schoolId: components["parameters"]["schoolId"];
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example stu_01
                 */
                studentId: components["parameters"]["studentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consulta exitosa. */
            200: {
                headers: {
                    /**
                     * @description Identificador para correlacionar respuesta y logs.
                     * @example trace_demo_01
                     */
                    "X-Trace-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "grd_01",
                     *           "subject": "Matemáticas",
                     *           "score": 6.5,
                     *           "weight": 0.3,
                     *           "comment": "Buen desempeño",
                     *           "date": "2026-10-08"
                     *         }
                     *       ],
                     *       "nextCursor": null
                     *     }
                     */
                    "application/json": components["schemas"]["GradePage"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            429: components["responses"]["429"];
            503: components["responses"]["503"];
        };
    };
    createGrade: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description UUID. Retención de 24 h por colegio, usuario y operación. Mismo payload reproduce status/body; payload diferente retorna 409.
                 * @example 60fae59e-e41c-4fe9-8a7a-51c8e3a301cc
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example sch_01
                 */
                schoolId: components["parameters"]["schoolId"];
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example stu_01
                 */
                studentId: components["parameters"]["studentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "subject": "Matemáticas",
                 *       "score": 6.5,
                 *       "weight": 0.3,
                 *       "comment": "Buen desempeño"
                 *     }
                 */
                "application/json": components["schemas"]["GradeInput"];
            };
        };
        responses: {
            /** @description Recurso creado. */
            201: {
                headers: {
                    /**
                     * @description Identificador para correlacionar respuesta y logs.
                     * @example trace_demo_01
                     */
                    "X-Trace-Id"?: string;
                    /**
                     * @description URI del recurso creado dentro del colegio.
                     * @example /students/stu_01/grades/grd_01
                     */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "grd_01",
                     *       "subject": "Matemáticas",
                     *       "score": 6.5,
                     *       "weight": 0.3,
                     *       "comment": "Buen desempeño",
                     *       "date": "2026-10-08"
                     *     }
                     */
                    "application/json": components["schemas"]["Grade"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            503: components["responses"]["503"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example sch_01
                 */
                schoolId: components["parameters"]["schoolId"];
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example stu_01
                 */
                studentId: components["parameters"]["studentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consulta exitosa. */
            200: {
                headers: {
                    /**
                     * @description Identificador para correlacionar respuesta y logs.
                     * @example trace_demo_01
                     */
                    "X-Trace-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "studentId": "stu_01",
                     *       "studentName": "Estudiante de prueba",
                     *       "generalAverage": 6.2,
                     *       "attendancePercentage": 94.5
                     *     }
                     */
                    "application/json": components["schemas"]["Report"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            429: components["responses"]["429"];
            503: components["responses"]["503"];
        };
    };
    createTutorQuery: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description UUID. Retención de 24 h por colegio, usuario y operación. Mismo payload reproduce status/body; payload diferente retorna 409.
                 * @example 60fae59e-e41c-4fe9-8a7a-51c8e3a301cc
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example sch_01
                 */
                schoolId: components["parameters"]["schoolId"];
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example crs_01
                 */
                courseId: components["parameters"]["courseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "question": "¿Cómo resuelvo una ecuación de primer grado?"
                 *     }
                 */
                "application/json": components["schemas"]["TutorQueryInput"];
            };
        };
        responses: {
            /** @description Recurso creado. */
            201: {
                headers: {
                    /**
                     * @description Identificador para correlacionar respuesta y logs.
                     * @example trace_demo_01
                     */
                    "X-Trace-Id"?: string;
                    /**
                     * @description URI del recurso creado dentro del colegio.
                     * @example /courses/crs_01/tutor-queries/tq_01
                     */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "tq_01",
                     *       "answer": "Aísla la incógnita aplicando la misma operación a ambos lados.",
                     *       "contentIds": [
                     *         "cnt_01"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["TutorQuery"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            503: components["responses"]["503"];
        };
    };
    createEvaluation: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description UUID. Retención de 24 h por colegio, usuario y operación. Mismo payload reproduce status/body; payload diferente retorna 409.
                 * @example 60fae59e-e41c-4fe9-8a7a-51c8e3a301cc
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example sch_01
                 */
                schoolId: components["parameters"]["schoolId"];
                /**
                 * @description Identificador del recurso dentro del colegio autorizado.
                 * @example crs_01
                 */
                courseId: components["parameters"]["courseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "title": "Evaluación de álgebra",
                 *       "contentIds": [
                 *         "cnt_01"
                 *       ],
                 *       "questionCount": 5
                 *     }
                 */
                "application/json": components["schemas"]["EvaluationInput"];
            };
        };
        responses: {
            /** @description Recurso creado. */
            201: {
                headers: {
                    /**
                     * @description Identificador para correlacionar respuesta y logs.
                     * @example trace_demo_01
                     */
                    "X-Trace-Id"?: string;
                    /**
                     * @description URI del recurso creado dentro del colegio.
                     * @example /courses/crs_01/evaluations/ev_01
                     */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "ev_01",
                     *       "title": "Evaluación de álgebra",
                     *       "questions": [
                     *         {
                     *           "prompt": "Resuelve x + 2 = 5",
                     *           "answer": "x = 3"
                     *         }
                     *       ],
                     *       "status": "draft"
                     *     }
                     */
                    "application/json": components["schemas"]["Evaluation"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            503: components["responses"]["503"];
        };
    };
}
